import { writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

import { defineCommand } from 'citty';

import { writeKeyPair } from '../keyfiles.js';
import { heading, item, ok, warn } from '../ui.js';

const CONFIG_FILE = 'pqc.config.json';

const CONFIG = {
  defaultAlgorithm: 'ml-kem-768',
  keysDir: 'keys',
} as const;

const EXAMPLE = `import { pqc } from '@pqc-sdk/core';

// Full roundtrip: generate keys, encrypt and decrypt.
const pair = await pqc.keys.generate(); // ML-KEM-768 by default
const ciphertext = await pqc.encrypt('hello post-quantum', pair.publicKey);
const plaintext = await pqc.decrypt(ciphertext, pair.secretKey);
console.log(new TextDecoder().decode(plaintext)); // "hello post-quantum"

// Digital signatures (ML-DSA-65):
const signer = await pqc.keys.generate({ algorithm: 'ml-dsa-65' });
const signature = await pqc.sign('document', signer.secretKey);
console.log(await pqc.verify('document', signature, signer.publicKey)); // true

// Keys serialize to base64url with metadata, ready to persist:
const token = pqc.keys.serialize(pair.publicKey);
console.log(token.slice(0, 48) + '…');

// To load the development keys generated by \`pqc init\`:
// import { readFile } from 'node:fs/promises';
// const publicKey = pqc.keys.deserialize(
//   (await readFile('keys/dev.public.pqc', 'utf8')).trim(),
// );
`;

export const init = defineCommand({
  meta: {
    name: 'init',
    description: 'Initialize a project: config, development keys and example',
  },
  async run() {
    if (existsSync(CONFIG_FILE)) {
      throw new Error(`${CONFIG_FILE} already exists: the project is already initialized.`);
    }

    await writeFile(CONFIG_FILE, `${JSON.stringify(CONFIG, null, 2)}\n`);
    const keys = await writeKeyPair(CONFIG.keysDir, 'dev', CONFIG.defaultAlgorithm, false);
    await writeFile('example.ts', EXAMPLE);

    heading('PQC project initialized:');
    item(`${CONFIG_FILE} — configuration with safe defaults`);
    item(`${keys.publicPath} / ${keys.secretPath} — development ${keys.algorithm} pair`);
    item('example.ts — full roundtrip ready to run');
    console.log();
    warn('The keys/dev.* keys are for development ONLY — do NOT use them in production.');
    ok(`Next step: run example.ts (node --experimental-strip-types example.ts or tsx)`);
  },
});
