import { hexToBytes } from '@noble/hashes/utils.js';
import { describe, expect, it } from 'vitest';

import type { KemAlgorithm } from './types.js';
import { pqc } from './index.js';
import { decryptStream, encryptStream } from './stream.js';
import golden from './vectors/golden-serialization-streaming.json';

/**
 * Golden serialization vectors for the streaming envelope
 * (docs/serialization-format.md §9) — the stability lock for the streaming
 * chunk-framing layout, companion to golden-vectors.test.ts (v1) and
 * golden-vectors-v2.test.ts (v2). Covers both KEMs (Days 1-2 of
 * docs/proposals/streaming-encryption.md). The fixture was generated by the
 * @pqc-sdk/core build that introduced streaming (see `meta.generatedWith`);
 * these tests deserialize and USE its artifacts on every run. If any of
 * them fails, a change broke the streaming format: that is a breaking
 * change requiring a major version bump, a docs/serialization-format.md
 * update and regenerated vectors in the same PR — never "fix" these tests
 * to match new output without that acknowledgment
 * (.claude/rules/crypto-review.md).
 */

// async is required to satisfy the AsyncIterable<Uint8Array> shape
// decryptStream/encryptStream take; nothing here genuinely needs to await.
// eslint-disable-next-line @typescript-eslint/require-await
async function* single(data: Uint8Array): AsyncGenerator<Uint8Array> {
  yield data;
}

async function collect(chunks: AsyncIterable<Uint8Array>): Promise<Uint8Array> {
  const parts: Uint8Array[] = [];
  let total = 0;
  for await (const chunk of chunks) {
    parts.push(chunk);
    total += chunk.length;
  }
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.length;
  }
  return out;
}

const cases: Array<{
  algorithm: KemAlgorithm;
  publicLength: number;
  secretLength: number;
  version: number;
  headerId: number;
}> = [
  {
    algorithm: 'ml-kem-768',
    publicLength: 1184,
    secretLength: 2400,
    version: 0x03,
    headerId: 0x01,
  },
  { algorithm: 'x-wing', publicLength: 1216, secretLength: 32, version: 0x04, headerId: 0x02 },
];

describe.each(cases)(
  'golden vectors streaming: $algorithm',
  ({ algorithm, publicLength, secretLength, version, headerId }) => {
    const publicToken = golden.keys[algorithm].publicToken;
    const secretToken = golden.keys[algorithm].secretToken;
    const ciphertextHex = golden.streaming[algorithm].ciphertextHex;

    it('deserializes the public and secret key tokens', () => {
      const publicKey = pqc.keys.deserialize(publicToken);
      const secretKey = pqc.keys.deserialize(secretToken);
      expect(publicKey.algorithm).toBe(algorithm);
      expect(publicKey.use).toBe('public');
      expect(publicKey.bytes.length).toBe(publicLength);
      expect(secretKey.algorithm).toBe(algorithm);
      expect(secretKey.use).toBe('secret');
      expect(secretKey.bytes.length).toBe(secretLength);
    });

    it('decrypts the golden streaming ciphertext to the exact expected plaintext', async () => {
      const secretKey = pqc.keys.deserialize(secretToken, { algorithm, use: 'secret' });
      const ciphertext = hexToBytes(ciphertextHex);
      const decrypted = await collect(decryptStream(secretKey, single(ciphertext)));
      expect(new TextDecoder().decode(decrypted)).toBe(golden.streaming.plaintextUtf8);
    });

    it('encrypts fresh data for the golden public key, decryptable by the golden secret key', async () => {
      const publicKey = pqc.keys.deserialize(publicToken, { algorithm, use: 'public' });
      const secretKey = pqc.keys.deserialize(secretToken, { algorithm, use: 'secret' });
      const plaintext = new TextEncoder().encode('fresh streamed message');
      const ciphertext = await collect(
        encryptStream(publicKey, single(plaintext), { chunkSize: golden.streaming.chunkSize }),
      );
      const decrypted = await collect(decryptStream(secretKey, single(ciphertext)));
      expect(new TextDecoder().decode(decrypted)).toBe('fresh streamed message');
    });

    it('sanity: the golden ciphertext carries the expected streaming header', () => {
      const bytes = hexToBytes(ciphertextHex);
      expect(bytes[0]).toBe(version);
      expect(bytes[1]).toBe(headerId);
    });
  },
);

describe('golden vectors streaming: fixture integrity', () => {
  it('records the generating version and the seeds that derive the keys', () => {
    expect(golden.meta.generatedWith).toMatch(/^@pqc-sdk\/core@0\.5\.\d+$/);
    expect(golden.meta.seeds['ml-kem-768']).toHaveLength(64 * 2);
    expect(golden.meta.seeds['x-wing']).toHaveLength(32 * 2);
    expect(golden.meta.chunkSize).toBe(8);
  });

  it('sanity: ml-kem-768 ciphertext length matches header + KEM ct + two 8-byte chunks + one 4-byte final chunk', () => {
    // "streaming golden vec" = 20 bytes at chunkSize=8: chunks of 8, 8, 4.
    const headerAndKem = 3 + 1088;
    const chunk0 = 8 + 16;
    const chunk1 = 8 + 16;
    const chunk2Final = 4 + 16;
    expect(golden.streaming['ml-kem-768'].ciphertextHex.length / 2).toBe(
      headerAndKem + chunk0 + chunk1 + chunk2Final,
    );
  });

  it('sanity: x-wing ciphertext length matches header + KEM ct + two 8-byte chunks + one 4-byte final chunk', () => {
    const headerAndKem = 3 + 1120;
    const chunk0 = 8 + 16;
    const chunk1 = 8 + 16;
    const chunk2Final = 4 + 16;
    expect(golden.streaming['x-wing'].ciphertextHex.length / 2).toBe(
      headerAndKem + chunk0 + chunk1 + chunk2Final,
    );
  });
});
