import { hexToBytes } from '@noble/hashes/utils.js';
import { describe, expect, it } from 'vitest';

import { pqc } from './index.js';
import golden from './vectors/golden-serialization-v3.json';

/**
 * Golden serialization vectors for envelope v3 (ml-kem-512) — the stability
 * lock for the pqcenc.v3 layout, companion to golden-vectors.test.ts (v1) and
 * golden-vectors-v2.test.ts (v2). The fixture was generated by the
 * @pqc-sdk/core build that introduced ml-kem-512 support (see
 * `meta.generatedWith`); these tests deserialize and USE its artifacts on
 * every run. If any of them fails, a change broke the v3 format: that is a
 * breaking change requiring a major version bump, a
 * docs/serialization-format.md update and regenerated vectors in the same PR
 * — never "fix" these tests to match new output without that acknowledgment
 * (.claude/rules/crypto-review.md).
 */

const utf8 = new TextEncoder();

const publicToken = golden.keys['ml-kem-512'].publicToken;
const secretToken = golden.keys['ml-kem-512'].secretToken;

describe('golden vectors v3: ml-kem-512 key tokens', () => {
  const cases = [
    { token: publicToken, use: 'public', length: 800 },
    { token: secretToken, use: 'secret', length: 1632 },
  ] as const;

  it.each(cases)('deserializes the ml-kem-512 $use token', ({ token, use, length }) => {
    const key = pqc.keys.deserialize(token);
    expect(key.algorithm).toBe('ml-kem-512');
    expect(key.use).toBe(use);
    expect(key.bytes.length).toBe(length);
  });

  it.each(cases)('round-trips the ml-kem-512 $use token byte-for-byte', ({ token }) => {
    // serialize(deserialize(t)) === t locks the canonical encoding itself.
    expect(pqc.keys.serialize(pqc.keys.deserialize(token))).toBe(token);
  });
});

describe('golden vectors v3: artifacts still work', () => {
  it('decrypts the golden v3 ciphertext to the exact expected plaintext', async () => {
    const secretKey = pqc.keys.deserialize(secretToken, { algorithm: 'ml-kem-512', use: 'secret' });
    const plaintext = await pqc.decrypt(hexToBytes(golden.encryption.ciphertextHex), secretKey);
    expect(new TextDecoder().decode(plaintext)).toBe(golden.encryption.plaintextUtf8);
  });

  it('encrypts fresh data for the golden public key, decryptable by the golden secret key', async () => {
    const publicKey = pqc.keys.deserialize(publicToken, { algorithm: 'ml-kem-512', use: 'public' });
    const secretKey = pqc.keys.deserialize(secretToken, { algorithm: 'ml-kem-512', use: 'secret' });
    const roundtrip = await pqc.decrypt(await pqc.encrypt('fresh message', publicKey), secretKey);
    expect(new TextDecoder().decode(roundtrip)).toBe('fresh message');
  });
});

describe('golden vectors v3: fixture integrity', () => {
  it('records the generating version and the seed that derives the keys', () => {
    expect(golden.meta.generatedWith).toMatch(/^@pqc-sdk\/core@0\.\d+\.\d+$/);
    expect(golden.meta.seeds['ml-kem-512']).toHaveLength(64 * 2);
  });

  it('sanity: the UTF-8 plaintext matches the ciphertext length (798-byte overhead)', () => {
    const plaintextLength = utf8.encode(golden.encryption.plaintextUtf8).length;
    expect(golden.encryption.ciphertextHex.length / 2).toBe(798 + plaintextLength);
  });

  it('sanity: the golden ciphertext carries the v3 header (0x03, 0x03)', () => {
    expect(golden.encryption.ciphertextHex.slice(0, 4)).toBe('0303');
  });
});
