import { hexToBytes } from '@noble/hashes/utils.js';
import { describe, expect, it } from 'vitest';

import { pqc } from './index.js';
import { decryptStream, encryptStream } from './stream.js';
import golden from './vectors/golden-serialization-streaming.json';

/**
 * Golden serialization vectors for the streaming envelope
 * (docs/serialization-format.md §9) — the stability lock for the streaming
 * chunk-framing layout, companion to golden-vectors.test.ts (v1) and
 * golden-vectors-v2.test.ts (v2). ml-kem-768 only on Day 1; x-wing joins
 * this fixture on Day 2. The fixture was generated by the @pqc-sdk/core
 * build that introduced streaming (see `meta.generatedWith`); these tests
 * deserialize and USE its artifacts on every run. If any of them fails, a
 * change broke the streaming format: that is a breaking change requiring a
 * major version bump, a docs/serialization-format.md update and
 * regenerated vectors in the same PR — never "fix" these tests to match new
 * output without that acknowledgment (.claude/rules/crypto-review.md).
 */

const publicToken = golden.keys['ml-kem-768'].publicToken;
const secretToken = golden.keys['ml-kem-768'].secretToken;

// async is required to satisfy the AsyncIterable<Uint8Array> shape
// decryptStream/encryptStream take; nothing here genuinely needs to await.
// eslint-disable-next-line @typescript-eslint/require-await
async function* single(data: Uint8Array): AsyncGenerator<Uint8Array> {
  yield data;
}

async function collect(chunks: AsyncIterable<Uint8Array>): Promise<Uint8Array> {
  const parts: Uint8Array[] = [];
  let total = 0;
  for await (const chunk of chunks) {
    parts.push(chunk);
    total += chunk.length;
  }
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.length;
  }
  return out;
}

describe('golden vectors streaming: ml-kem-768 key tokens', () => {
  const cases = [
    { token: publicToken, use: 'public', length: 1184 },
    { token: secretToken, use: 'secret', length: 2400 },
  ] as const;

  it.each(cases)('deserializes the ml-kem-768 $use token', ({ token, use, length }) => {
    const key = pqc.keys.deserialize(token);
    expect(key.algorithm).toBe('ml-kem-768');
    expect(key.use).toBe(use);
    expect(key.bytes.length).toBe(length);
  });
});

describe('golden vectors streaming: artifacts still work', () => {
  it('decrypts the golden streaming ciphertext to the exact expected plaintext', async () => {
    const secretKey = pqc.keys.deserialize(secretToken, {
      algorithm: 'ml-kem-768',
      use: 'secret',
    });
    const ciphertext = hexToBytes(golden.streaming.ciphertextHex);
    const decrypted = await collect(decryptStream(secretKey, single(ciphertext)));
    expect(new TextDecoder().decode(decrypted)).toBe(golden.streaming.plaintextUtf8);
  });

  it('encrypts fresh data for the golden public key, decryptable by the golden secret key', async () => {
    const publicKey = pqc.keys.deserialize(publicToken, {
      algorithm: 'ml-kem-768',
      use: 'public',
    });
    const secretKey = pqc.keys.deserialize(secretToken, {
      algorithm: 'ml-kem-768',
      use: 'secret',
    });
    const plaintext = new TextEncoder().encode('fresh streamed message');
    const ciphertext = await collect(
      encryptStream(publicKey, single(plaintext), { chunkSize: golden.streaming.chunkSize }),
    );
    const decrypted = await collect(decryptStream(secretKey, single(ciphertext)));
    expect(new TextDecoder().decode(decrypted)).toBe('fresh streamed message');
  });
});

describe('golden vectors streaming: fixture integrity', () => {
  it('records the generating version and the seed that derives the key', () => {
    expect(golden.meta.generatedWith).toMatch(/^@pqc-sdk\/core@0\.5\.\d+$/);
    expect(golden.meta.seeds['ml-kem-768']).toHaveLength(64 * 2);
    expect(golden.meta.chunkSize).toBe(8);
  });

  it('sanity: the golden ciphertext carries the streaming ml-kem-768 header (0x03, 0x01, chunkSize exponent 3)', () => {
    expect(golden.streaming.ciphertextHex.slice(0, 6)).toBe('030103');
  });

  it('sanity: ciphertext length matches header + KEM ct + two 8-byte chunks + one 4-byte final chunk', () => {
    // "streaming golden vec" = 20 bytes at chunkSize=8: chunks of 8, 8, 4.
    const headerAndKem = 3 + 1088;
    const chunk0 = 8 + 16;
    const chunk1 = 8 + 16;
    const chunk2Final = 4 + 16;
    expect(golden.streaming.ciphertextHex.length / 2).toBe(
      headerAndKem + chunk0 + chunk1 + chunk2Final,
    );
  });
});
