import { describe, expect, it } from 'vitest';

import { pqc } from './index.js';
import type { SecretKey, SignatureAlgorithm } from './types.js';
import { ml_dsa44, ml_dsa65, ml_dsa87 } from './vendor/ml-dsa/ml-dsa.js';
import { ml_kem768 } from './vendor/ml-kem/ml-kem.js';
import circlMldsa from './vectors/interop/circl-mldsa.json';
import circlMlkem768 from './vectors/interop/circl-mlkem768.json';
import circlXwing from './vectors/interop/circl-xwing.json';
import { ml_kem768_x25519 } from './x-wing.js';

const MLDSA_SIGNERS = { '44': ml_dsa44, '65': ml_dsa65, '87': ml_dsa87 } as const;

function mldsaPublicKey(set: string, token: string) {
  const algorithm = `ml-dsa-${set}` as SignatureAlgorithm;
  return pqc.keys.deserialize(token, { algorithm, use: 'public' });
}

function mldsaSignerFor(set: string) {
  const signer = MLDSA_SIGNERS[set as keyof typeof MLDSA_SIGNERS];
  if (!signer) throw new Error(`unknown ML-DSA set ${set}`);
  return signer;
}

/**
 * Cross-implementation interop regression guard, in two parts with different
 * scope — read both before trusting either.
 *
 * **Part 1 (cross-check regression guard).** The vectors were produced by
 * scripts/interop/generate-circl-vectors.mts cross-checking this SDK against
 * Cloudflare's CIRCL (Go) — an independent codebase, not the
 * @noble/post-quantum family this SDK is built on. That cross-check (does
 * CIRCL accept what the SDK produced; does the SDK accept what CIRCL
 * produced) happened once, at generation time, and is NOT repeated here:
 * Go/CIRCL never runs in CI. These tests only re-verify/re-decapsulate the
 * already-committed bytes — they never call sign() or encapsulate() — so a
 * regression here means the SDK's verify()/decapsulate() no longer agrees
 * with what CIRCL already validated. See each vector file's `meta` block for
 * exactly what was cross-checked and how to reproduce it.
 *
 * **Part 2 ("round-trip" — the "does the SDK still exercise sign()/
 * encapsulate() itself" checks below).** A prior audit found that Part 1's
 * design has a real gap: because it never calls sign()/encapsulate(), a
 * mutation that made the vendored ML-DSA sign() return garbage passed all of
 * Part 1's tests — nothing exercises the generation path, only verification
 * of pre-generated bytes. The tests below close that specific gap by calling
 * pqc.sign()/encapsulate() fresh, every run, using the same key material
 * CIRCL already cross-checked, and confirming the freshly-produced output is
 * still accepted by this SDK's own verify()/decapsulate().
 *
 * **What Part 2 does NOT prove, stated plainly so it is never read as live
 * cross-implementation verification:** it does not call CIRCL. A signature or
 * ciphertext this SDK produces today is checked against this SDK's own
 * verify()/decapsulate() only — self-consistency, not a fresh interop claim.
 * If this SDK's sign() and verify() regressed identically (a real but
 * unlikely failure mode — e.g. both sides silently agreeing on a wrong
 * format), Part 2 would not catch it; only regenerating against CIRCL (a
 * human-run step) would. What Part 2 *does* guarantee is that sign()/
 * encapsulate() are still being exercised on every CI run, against key
 * material an independent implementation has already validated — so a
 * broken generator fails loudly here instead of shipping silently until
 * someone next regenerates the vectors.
 */

const hexToBytes = (hex: string) => new Uint8Array(Buffer.from(hex, 'hex'));

describe('CIRCL interop: ML-DSA-44/65/87 signature generation', () => {
  it.each(circlMldsa.cases)(
    'ML-DSA-$set: the SDK still accepts both its own and CIRCL-produced signature',
    async ({ set, publicKeyToken, message, sdkSignatureHex, circlSignatureHex }) => {
      const publicKey = mldsaPublicKey(set, publicKeyToken);

      await expect(pqc.verify(message, hexToBytes(sdkSignatureHex), publicKey)).resolves.toBe(true);
      await expect(pqc.verify(message, hexToBytes(circlSignatureHex), publicKey)).resolves.toBe(
        true,
      );
    },
  );

  it("does not accept a CIRCL signature under a different set's message", async () => {
    // Cheap mutation check: swapping the message must break verification of a
    // genuinely independent (CIRCL-produced) signature, same as any other.
    const [first, second] = circlMldsa.cases;
    if (!first || !second) throw new Error('expected at least two ML-DSA cases in the fixture');
    const publicKey = mldsaPublicKey(first.set, first.publicKeyToken);
    await expect(
      pqc.verify(second.message, hexToBytes(first.circlSignatureHex), publicKey),
    ).resolves.toBe(false);
  });

  // --- Round-trip (see "Part 2" in the module doc comment above) ---
  it.each(circlMldsa.cases)(
    'ML-DSA-$set round-trip: pqc.sign(), called fresh right now, still verifies against the CIRCL-cross-checked public key',
    async ({ set, seedHex, publicKeyToken, message }) => {
      const signer = mldsaSignerFor(set);
      const seed = hexToBytes(seedHex);
      const { publicKey, secretKey } = signer.keygen(seed);

      // Sanity: the committed seed must still derive the exact public key
      // CIRCL cross-checked — if this fails, keygen() itself regressed, which
      // would make the "round-trip" below meaningless (right answer, wrong key).
      const publicKeyFromToken = mldsaPublicKey(set, publicKeyToken);
      expect(Buffer.from(publicKey).toString('hex')).toBe(
        Buffer.from(publicKeyFromToken.bytes).toString('hex'),
      );

      const algorithm = `ml-dsa-${set}` as SignatureAlgorithm;
      const secretKeyObj: SecretKey<SignatureAlgorithm> = {
        algorithm,
        use: 'secret',
        bytes: secretKey,
      };

      // The real public entry point — pqc.sign() — not the vendored primitive
      // directly, unlike the generator's own Direction A (see
      // scripts/interop/generate-circl-vectors.mts for why that one stays on
      // the vendored path: it needs deterministic output, which pqc.sign()
      // cannot produce by design — extraEntropy is deliberately unreachable
      // through it).
      const freshSignature = await pqc.sign(message, secretKeyObj);
      await expect(pqc.verify(message, freshSignature, publicKeyFromToken)).resolves.toBe(true);
    },
  );
});

describe('CIRCL interop: X-Wing bidirectional shared-secret cross-check', () => {
  const {
    publicKeyHex,
    secretKeyHex,
    sdkCiphertextHex,
    sdkSharedSecretHex,
    circlCiphertextHex,
    circlSharedSecretHex,
  } = circlXwing.case;
  const secretKey = hexToBytes(secretKeyHex);

  it('the SDK still decapsulates its own committed ciphertext to the committed shared secret', () => {
    const sharedSecret = ml_kem768_x25519.decapsulate(hexToBytes(sdkCiphertextHex), secretKey);
    expect(Buffer.from(sharedSecret).toString('hex')).toBe(sdkSharedSecretHex);
  });

  it("the SDK's decapsulate still agrees with CIRCL's committed ciphertext and shared secret", () => {
    // This is the direction that matters most: CIRCL — a genuinely independent
    // codebase — produced this ciphertext once, at generation time. Every CI
    // run re-checks that this SDK's decapsulate() still processes it correctly.
    const sharedSecret = ml_kem768_x25519.decapsulate(hexToBytes(circlCiphertextHex), secretKey);
    expect(Buffer.from(sharedSecret).toString('hex')).toBe(circlSharedSecretHex);
  });

  it('a tampered CIRCL ciphertext no longer reproduces the committed shared secret', () => {
    const tampered = hexToBytes(circlCiphertextHex);
    tampered[0] = (tampered[0] ?? 0) ^ 0xff;
    const sharedSecret = ml_kem768_x25519.decapsulate(tampered, secretKey);
    expect(Buffer.from(sharedSecret).toString('hex')).not.toBe(circlSharedSecretHex);
  });

  // --- Round-trip (see "Part 2" in the module doc comment above) ---
  it('round-trip: encapsulate(), called fresh right now, still decapsulates correctly against the CIRCL-cross-checked key', () => {
    const publicKey = hexToBytes(publicKeyHex);
    const { cipherText, sharedSecret } = ml_kem768_x25519.encapsulate(publicKey);
    const recovered = ml_kem768_x25519.decapsulate(cipherText, secretKey);
    expect(Buffer.from(recovered).toString('hex')).toBe(Buffer.from(sharedSecret).toString('hex'));
  });
});

describe('CIRCL interop: ML-KEM-768 bidirectional shared-secret cross-check', () => {
  const {
    publicKeyHex,
    secretKeyHex,
    sdkCiphertextHex,
    sdkSharedSecretHex,
    circlCiphertextHex,
    circlSharedSecretHex,
  } = circlMlkem768.case;
  const secretKey = hexToBytes(secretKeyHex);

  it('the SDK still decapsulates its own committed ciphertext to the committed shared secret', () => {
    const sharedSecret = ml_kem768.decapsulate(hexToBytes(sdkCiphertextHex), secretKey);
    expect(Buffer.from(sharedSecret).toString('hex')).toBe(sdkSharedSecretHex);
  });

  it("the SDK's decapsulate still agrees with CIRCL's committed ciphertext and shared secret", () => {
    const sharedSecret = ml_kem768.decapsulate(hexToBytes(circlCiphertextHex), secretKey);
    expect(Buffer.from(sharedSecret).toString('hex')).toBe(circlSharedSecretHex);
  });

  it('a tampered CIRCL ciphertext no longer reproduces the committed shared secret', () => {
    const tampered = hexToBytes(circlCiphertextHex);
    tampered[0] = (tampered[0] ?? 0) ^ 0xff;
    const sharedSecret = ml_kem768.decapsulate(tampered, secretKey);
    expect(Buffer.from(sharedSecret).toString('hex')).not.toBe(circlSharedSecretHex);
  });

  // --- Round-trip (see "Part 2" in the module doc comment above) ---
  it('round-trip: encapsulate(), called fresh right now, still decapsulates correctly against the CIRCL-cross-checked key', () => {
    const publicKey = hexToBytes(publicKeyHex);
    const { cipherText, sharedSecret } = ml_kem768.encapsulate(publicKey);
    const recovered = ml_kem768.decapsulate(cipherText, secretKey);
    expect(Buffer.from(recovered).toString('hex')).toBe(Buffer.from(sharedSecret).toString('hex'));
  });
});
